name: "quay"
version: "0.7.1"
usage: "app-registry client to Helm"
description: |-
  This plugin provides app-registry client to Helm.
  usage:
    $ helm quay install quay.io/charts/gitlab-ce --namespace ci
    $ helm quay upgrade quay.io/charts/jenkins --set imageTag=latest
ignoreFlags: false
useTunnel: false
platformCommand:
  - os: darwin
    command: "$HELM_PLUGIN_DIR/cnr.sh"
  - os: linux
    command: "$HELM_PLUGIN_DIR/cnr.sh"
  - os: windows
    command: "powershell $HELM_PLUGIN_DIR/cnr.ps1"
